VO_Quests/ViewModels/Quest/QuestDetailsVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VO_Quests.Models;

namespace VO_Quests.UI.ViewModels
{
    public class QuestDetailsVM
    {
        public string QuestName { get; set; }
        public string PosterPath { get; set; }
        public IEnumerable<QuestSlotAvailability> Slots { get; set; }
        public int QuestId { get; internal set; }
    }
}

VO_Quests/Controllers/QuestController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VO_Quests.Abstraction;
using VO_Quests.UI.ViewModels;

namespace VO_Quests.Controllers
{
    public class QuestController : BaseController
    {
        public QuestController(IUnitOfWork uow) : base(uow)
        {

        }

        public IActionResult List()
        {
            var quest = _uow.Quests.GetAllQuests();

            return View(quest);
        }

        [Authorize]
        public IActionResult Details(int id)
        {
            var quest = _uow.Quests.GetById(id);

            var questSlots = _uow.Reservations.GetQuestSlots(id);


            var model = new QuestDetailsVM()
            {
                QuestId = quest.Id,
                QuestName = quest.QuestName,
                PosterPath = quest.PosterPath,
                Slots = questSlots
            };

            return View(model);
        }
    }
}

VO_Quests/Controllers/ReservationController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using VO_Quests.Abstraction;
using VO_Quests.Models;
using VO_Quests.UI.ViewModels.Reserve;

namespace VO_Quests.Controllers
{
    public class ReservationController : BaseController
    {
        private UserManager<ApplicationUser> _userManager;
        public ReservationController(IUnitOfWork uow, UserManager<ApplicationUser> userManager) : base(uow)
        {
            _userManager = userManager;
        }
        
        public async Task<IActionResult> CreateNewReservation(NewReservationVM newReservation)
        {
            var user = await _userManager.GetUserAsync(User);

            var reservatingResult = _uow.Reservations.AddNewReservation(new Reservation()
            {
                SlotDate = newReservation.SlotDate,
                CreateDate = DateTimeOffset.Now,
                QuestId = newReservation.QuestId,
                UserId = user.Id
            });


            return View("Result", reservatingResult);
        }
    }
}

VO_Quests/Views/Quest/Details.cshtml
@model QuestDetailsVM
@{
    ViewData["Title"] = "Home Page";
}


<div class="row container-quests">
    <div class="col-xs-12">
        <h2>@Model.QuestName</h2>
        <img class="quest-img" src="@Model.PosterPath" alt="@Model.QuestName" />
        <form asp-action="CreateNewReservation" asp-controller="Reservation">
            @Html.HiddenFor(f => f.QuestId)
            <select name="SlotDate">
                <option></option>
                @foreach (var slot in Model.Slots)
                {
                    <option disabled="@(slot.IsAllowed ? null : "disabled")"  value="@(slot.SlotDate)">@slot.SlotDate.DateTime</option>
                }
            </select>
            <button class="btn btn-primary" type="submit">Book!</button>
        </form>

    </div>
</div>

VO_Quests/Views/Quest/List.cshtml
@model IEnumerable<Quest>
@{
    ViewData["Title"] = "Home Page";
}


<div class="row container-quests">
    <div class="col-xs-12">
        <h2>Our Quests</h2>
        <ul class="quests-list row">
            @foreach (var quest in Model)
            {
                <li class="col-xs-4">
                    <div class="card" style="width: 20rem;">
                        <div class="card-img-top" style="background-image:url('@quest.PosterPath')"></div>
                        <div class="card-block">
                            <h4 class="card-title">@quest.QuestName</h4>
                            <a asp-route-id="@quest.Id" asp-controller="Quest" asp-action="Details" class="btn btn-primary">Go to quest</a>
                        </div>
                    </div>
                </li>
            }
        </ul>
    </div>
</div>